// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3r2d9j9wSF2_1NiUaiMNPz34qjiQLXG8',
    appId: '1:683674184071:web:43e7689859c21e527acb22',
    messagingSenderId: '683674184071',
    projectId: 'selah-holybible-29f4d',
    authDomain: 'selah-holybible-29f4d.firebaseapp.com',
    storageBucket: 'selah-holybible-29f4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGZhNHWHKS6RS0-5f61z2C-xc95qvthGE',
    appId: '1:683674184071:android:5a4b688b9dc81a717acb22',
    messagingSenderId: '683674184071',
    projectId: 'selah-holybible-29f4d',
    storageBucket: 'selah-holybible-29f4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbkFJNpGPANGQ72BXRAp24DtIlJGty1Iw',
    appId: '1:683674184071:ios:ef832205be0a36f67acb22',
    messagingSenderId: '683674184071',
    projectId: 'selah-holybible-29f4d',
    storageBucket: 'selah-holybible-29f4d.firebasestorage.app',
    iosBundleId: 'com.selah.holybible',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbkFJNpGPANGQ72BXRAp24DtIlJGty1Iw',
    appId: '1:683674184071:ios:ef832205be0a36f67acb22',
    messagingSenderId: '683674184071',
    projectId: 'selah-holybible-29f4d',
    storageBucket: 'selah-holybible-29f4d.firebasestorage.app',
    iosBundleId: 'com.selah.holybible',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3r2d9j9wSF2_1NiUaiMNPz34qjiQLXG8',
    appId: '1:683674184071:web:d4292e90f8132dc57acb22',
    messagingSenderId: '683674184071',
    projectId: 'selah-holybible-29f4d',
    authDomain: 'selah-holybible-29f4d.firebaseapp.com',
    storageBucket: 'selah-holybible-29f4d.firebasestorage.app',
  );
}
